name: CI

on: [push, pull_request]

jobs:
  nstack:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.1.0
    - name: default build
      run: make
  tnetcat:
    runs-on: self-hosted
    container: 
      image: catthehacker/ubuntu:act-latest
      options: --privileged
    steps:
    - uses: actions/checkout@v3.1.0
    - name: tnetcat test
      run: |
          apt-get update;
          sudo apt-get install -q -y iproute2
          sudo apt-get install -q -y netcat
          sh .ci/test-tnetcat.sh
      shell: bash
  unetcat:
    runs-on: self-hosted
    container: 
      image: catthehacker/ubuntu:act-latest
      options: --privileged
    steps:
    - uses: actions/checkout@v3.1.0
    - name: unetcat test
      run: |
          apt-get update;
          sudo apt-get install -q -y iproute2
          sudo apt-get install -q -y netcat
          sh .ci/test-unetcat.sh
      shell: bash
  tcptest:
    runs-on: self-hosted
    container: 
      image: catthehacker/ubuntu:act-latest
      options: --privileged
    steps:
    - uses: actions/checkout@v3.1.0
    - name: tcp sending test
      run: |
          apt-get update;
          sudo apt-get install -q -y iproute2
          sudo apt-get install -q -y netcat
          sh .ci/test-tcptest.sh
      shell: bash
  coding_style:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3.1.0
    - name: coding convention
      run: |
            sudo apt-get install -q -y clang-format-12
            sh .ci/check-format.sh
      shell: bash
